
services:
  auth-db:
    image: postgres:latest
    networks:
      - traefik
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
      - POSTGRES_PASSWORD=SUPERsecret
    volumes:
      - auth_db:/var/lib/postgresql/data

  auth:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    networks:
      - traefik
    depends_on:
      - auth-db
    volumes:
      - ./kc/stigman_realm.json:/opt/keycloak/data/import/stigman_realm.json
    environment:
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME=keycloak.local.guatalupe.com
      - KC_HTTP_ENABLED=true
      - KC_PROXY_HEADERS=xforwarded
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=SUPERsecret
      - KC_DB_URL_HOST=auth-db
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.local.guatalupe.com`)"
      - "traefik.http.routers.keycloak.entrypoints=https"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    command: start --import-realm

volumes:
  auth_db:
networks:
  traefik:
    external: true
